/*
   Implement Twitter/Weibo @ mentions

   Copyright (c) 2012 chord.luo@gmail.com

   Permission is hereby granted, free of charge, to any person obtaining
   a copy of this software and associated documentation files (the
   "Software"), to deal in the Software without restriction, including
   without limitation the rights to use, copy, modify, merge, publish,
   distribute, sublicense, and/or sell copies of the Software, and to
   permit persons to whom the Software is furnished to do so, subject to
   the following conditions:

   The above copyright notice and this permission notice shall be
   included in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
   LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
   OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
   WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
(function(){var c=window.jQuery,f,m;f=function(c){var e,l,f,j;if(document.selection){if((l=document.selection.createRange())&&l.parentElement()===c)e=c.value.replace(/\r\n/g,"\n"),e=e.length,j=c.createTextRange(),j.moveToBookmark(l.getBookmark()),c=c.createTextRange(),c.collapse(!1),-1<j.compareEndPoints("StartToEnd",c)?f=e:(f=-j.moveStart("character",-e),j.moveEnd("character",-e))}else f=c.selectionStart;return f};m=function(c,e){var f;return document.selection?(f=c.createTextRange(),f.move("character",
e),f.select()):c.setSelectionRange(e,e)};c.fn.caretPos=function(c){var e;e=this[0];e.focus();return c?m(e,c):f(e)}}).call(this);(function(){var c=window.jQuery,f,m,n,e,l,p,j,h,q,r,s;n={$mirror:null,css:"overflowY height width paddingTop paddingLeft paddingRight paddingBottom marginTop marginLeft marginRight marginBottom fontFamily borderStyle borderWidth wordWrap fontSize lineHeight overflowX".split(" "),init:function(a){var b,d;b=c("<div></div>");d={position:"absolute",left:-9999,top:0,zIndex:-2E4,"white-space":"pre-wrap"};c.each(this.css,function(b,c){return d[c]=a.css(c)});b.css(d);this.$mirror=b;a.after(b);return this},
setContent:function(a){this.$mirror.html(a);return this},getFlagRect:function(){var a,b;a=this.$mirror.find("span#flag");b=a.position();a={left:b.left,top:b.top,bottom:a.height()+b.top};this.$mirror.remove();return a}};f=function(a){var b=this;a=this.$inputor=c(a);this.options={};this.query={text:"",start:0,stop:0};this._cache={};this.pos=0;this.flags={};this.theflag=null;this.search_word={};this.view=m;this.mirror=n;a.on("keyup.inputor",function(a){if(!(40===a.keyCode||38===a.keyCode)||!b.view.isShowing())return b.lookup()});
this.init();e("At.new",a[0]);return this};f.prototype={constructor:f,init:function(){var a=this;this.$inputor.on("keyup.inputor",function(b){return a.onkeyup(b)}).on("keydown.inputor",function(b){return a.onkeydown(b)}).on("scroll.inputor",function(){return a.view.hide()}).on("blur.inputor",function(){return a.view.hide(1E3)});return e("At.init",this.$inputor[0])},reg:function(a,b){var d,g,k;d={};c.isFunction(b)?d.callback=b:d=b;k=(g=this.options)[a]||(g[a]=c.fn.atWho["default"]);this.options[a]=
c.extend({},k,d);return e("At.reg",this.$inputor[0],a,b)},dataValue:function(){var a;if(a=this.search_word[this.theflag])return a;a=/data-value=["']?\$\{(\w+)\}/g.exec(this.getOpt("tpl"));return this.search_word[this.theflag]=!h(a)?a[1]:null},getOpt:function(a){try{return this.options[this.theflag][a]}catch(b){return null}},rect:function(){var a,b,d,g;a=this.$inputor;if(document.selection)return b=document.selection.createRange(),g=b.boundingLeft+a.scrollLeft(),a=b.boundingTop+c(window).scrollTop()+
a.scrollTop(),d=a+b.boundingHeight,{top:a-2,left:g-2,bottom:d-2};g="<span>"+a.val().slice(0,this.pos-1).replace(/</g,"&lt").replace(/>/g,"&gt").replace(/`/g,"&#96").replace(/"/g,"&quot").replace(/\r\n|\r|\n/g,"<br />")+"</span>";g+="<span id='flag'>@</span>";d=a.offset();b=this.mirror.init(a).setContent(g).getFlagRect();g=d.left+b.left-a.scrollLeft();a=d.top-a.scrollTop();d=a+b.bottom;a+=b.top;return{top:a,left:g,bottom:d+2}},cache:function(a){var b,d;b=this.query.text;return!this.getOpt("cache")||
!b?null:(d=this._cache)[b]||(d[b]=a)},getKeyname:function(){var a,b,d,g,k,f=this;a=this.$inputor;g=a.val();a=a.caretPos();k=g.slice(0,a);d=null;c.each(this.options,function(a){var b;b=RegExp(a+"([A-Za-z0-9_+-]*)$|"+a+"([^\\x00-\\xff]*)$","gi").exec(k);if(!h(b))return d=b[2]?b[2]:b[1],f.theflag=a,!1});"string"===typeof d&&20>=d.length?(g=a-d.length,b=g+d.length,this.pos=g,b={text:d.toLowerCase(),start:g,end:b}):this.view.hide();e("At.getKeyname",b);return this.query=b},replaceStr:function(a){var b,
d,c,k;b=this.$inputor;c=this.query;k=b.val();d=this.getOpt("display_flag")?0:this.theflag.length;d=k.slice(0,c.start-d);c=d+a+k.slice(c.end);b.val(c);b.caretPos(d.length+a.length);b.change();return e("At.replaceStr",c)},onkeyup:function(a){var b;b=this.view;if(b.isShowing()){switch(a.keyCode){case 27:a.preventDefault();b.hide();break;default:c.noop()}return a.stopPropagation()}},onkeydown:function(a){var b;b=this.view;if(b.isShowing()){switch(a.keyCode){case 27:a.preventDefault();b.hide();break;case 38:a.preventDefault();
b.prev();break;case 40:a.preventDefault();b.next();break;case 9:case 13:if(!b.isShowing())return;a.preventDefault();b.choose();break;default:c.noop()}return a.stopPropagation()}},renderView:function(a){e("At.renderView",this,a);a=a.splice(0,this.getOpt("limit"));a=s(a,this.dataValue());a=q(a);a=r.call(this,a);return this.view.render(this,a)},lookup:function(){var a,b,d;if(d=this.getKeyname())return e("At.lookup.key",d),h(b=this.cache())?h(b=this.lookupWithData(d))?c.isFunction(a=this.getOpt("callback"))?
a(d.text,c.proxy(this.renderView,this)):this.view.hide():this.renderView(b):this.renderView(b),c.noop()},lookupWithData:function(a){var b,d,g=this;b=this.getOpt("data");c.isArray(b)&&0!==b.length&&(d=c.map(b,function(b){var d,e,f;try{e=c.isPlainObject(b)?b[g.dataValue()]:b,f=RegExp(a.text.replace("+","\\+"),"i"),d=e.match(f)}catch(h){return null}return d?b:null}));return d}};m={timeout_id:null,id:"#at-view",holder:null,_jqo:null,jqo:function(){var a;a=this._jqo;return h(a)?this._jqo=c(this.id):a},
init:function(){var a,b,d=this;if(h(this.jqo()))return b="<div id='"+this.id.slice(1)+"' class='at-view'><ul id='"+this.id.slice(1)+"-ul'></ul></div>",c("body").append(b),a=this.jqo().find("ul"),a.on("mouseenter.view","li",function(b){a.find(".cur").removeClass("cur");return c(b.currentTarget).addClass("cur")}).on("click",function(a){a.stopPropagation();a.preventDefault();return d.choose()})},isShowing:function(){return this.jqo().is(":visible")},choose:function(){var a;a=this.jqo().find(".cur");
a=h(a)?this.holder.query.text+" ":a.attr(this.holder.getOpt("choose"))+" ";this.holder.replaceStr(a);return this.hide()},rePosition:function(){var a;a=this.holder.rect();a.bottom+this.jqo().height()-c(window).scrollTop()>c(window).height()&&(a.bottom=a.top-this.jqo().height());e("AtView.rePosition",{left:a.left,top:a.bottom});return this.jqo().offset({left:a.left,top:a.bottom})},next:function(){var a;a=this.jqo().find(".cur").removeClass("cur").next();a.length||(a=c(this.jqo().find("li")[0]));return a.addClass("cur")},
prev:function(){var a;a=this.jqo().find(".cur").removeClass("cur").prev();a.length||(a=this.jqo().find("li").last());return a.addClass("cur")},show:function(){this.isShowing()||this.jqo().show();return this.rePosition()},hide:function(a){var b=this;if(isNaN(a)){if(this.isShowing())return this.jqo().hide()}else return a=function(){return b.hide()},clearTimeout(this.timeout_id),this.timeout_id=setTimeout(a,300)},clear:function(a){!0===a&&(this._cache={});return this.jqo().find("ul").empty()},render:function(a,
b){var d,g;if(!c.isArray(b))return!1;if(0>=b.length)return this.hide(),!0;this.holder=a;a.cache(b);this.clear();d=this.jqo().find("ul");g=a.getOpt("tpl");c.each(b,function(b,c){var f;g||(g=l);f=p(g,c);e("AtView.render",f);return d.append(j(f,a.query.text))});this.show();return d.find("li:eq(0)").addClass("cur")}};q=function(a){return c.map(a,function(a,d){c.isPlainObject(a)||(a={id:d,name:a});return a})};p=function(a,b){try{return a.replace(/\$\{([^\}]*)\}/g,function(a,d){return b[d]})}catch(d){return""}};
j=function(a,b){return h(b)?a:a.replace(RegExp(">\\s*(\\w*)("+b.replace("+","\\+")+")(\\w*)\\s*<","ig"),function(a,b,c,e){return"> "+b+"<strong>"+c+"</strong>"+e+" <"})};r=function(a){var b,d,c,e,f,h,j;b=this.dataValue();c=this.query.text;e=[];h=0;for(j=a.length;h<j;h++)d=a[h],f=d[b],-1!==f.toLowerCase().indexOf(c)&&(d.order=f.toLowerCase().indexOf(c),e.push(d));e.sort(function(a,b){return a.order-b.order});return e};s=function(a,b){var d;d=[];return c.map(a,function(a){var e;e=c.isPlainObject(a)?
a[b]:a;if(0>c.inArray(e,d))return d.push(e),a})};h=function(a){return!a||c.isPlainObject(a)&&c.isEmptyObject(a)||c.isArray(a)&&0===a.length||a instanceof c&&0===a.length||void 0===a};l="<li id='${id}' data-value='${name}'>${name}</li>";e=function(){};c.fn.atWho=function(a,b){m.init();return this.filter("textarea, input").each(function(){var d,e;d=c(this);(e=d.data("AtWho"))||d.data("AtWho",e=new f(this));return e.reg(a,b)})};c.fn.atWho["default"]={data:[],choose:"data-value",callback:null,cache:!0,
limit:5,display_flag:!0,tpl:l}}).call(this);